#!/bin/sh
backup_dir="/home/pi/treeLights/"

if [ -z "$1" ]
	then
		read -p "Please supply a description of the changes" message
	else
		message=$1
fi


cd $backup_dir
git add *
git commit -am "$message"
git push origin master
